# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HY3Ac1epSFEYM4bIMx3DVqGYeLSwH5V9
"""

import streamlit as st

# Set the title of the app
st.title("User Information Input App")

# Input fields for user information
name = st.text_input("Enter your name:")
age = st.number_input("Enter your age:", min_value=0, max_value=120, value=25)
major = st.text_input("Enter your major:")

# Button to submit the information
if st.button("Submit"):
    # Display the inputted information
    st.write(f"Hello, {name}! You are {age} years old.")
    st.write(f"Your major is:")
    st.markdown(f"<div style='width:100px; height:100px; background-color:{major};'></div>", unsafe_allow_html=True)

# Optional: Add a reset button
if st.button("Reset"):
    st.experimental_rerun()